# Generated by Django 5.2.14 on 2026-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("ministry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="ministry.userrole",
                verbose_name="ministry roles",
            ),
        ),
    ]
