# Generated by Django 5.2.15 on 2026-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('ministry', '0002_kolekte_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pelayanan_categories',
            field=models.ManyToManyField(blank=True, related_name='eligible_users', to='ministry.pelayanan', verbose_name='service categories'),
        ),
    ]
